# Generated by Django 4.1.4 on 2022-12-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_remove_usermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
