# Generated by Django 4.1.4 on 2022-12-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Scotch', 'Scotch'), ('Bourbon', 'Bourbon'), ('Irish', 'Irish')], max_length=7)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=3)),
                ('description', models.TextField(max_length=500)),
                ('image', models.URLField()),
            ],
        ),
    ]
